DROP DATABASE if EXISTS burgers_db;
Create DATABASE burgers_db;

USE burgers_db;



CREATE TABLE burgers (
    id INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(50)NOT NULL,
    devoured boolean NOT NULL DEFAULT 0,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (id)
);